version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: codegroup
      POSTGRES_USER: jocar
      POSTGRES_PASSWORD: banco123
    ports:
      - "5432:5432"
    #volumes:
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
  your-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
